# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Pod Install"
  lane :pod_install do
    cocoapods(
      clean_install: false,
      use_bundle_exec: true,
      repo_update: true
    )
  end

  desc "Build & Run Unit Testing" 
  lane :build_for_testing do
    run_tests(
      workspace: "AlfaResto-RestoApp.xcworkspace",
      scheme: "AlfaResto-RestoApp",
      clean: true,
      skip_slack: true,
      result_bundle: true,
      output_xctestrun: true,
      build_for_testing: true,
      device: "iPhone 14 Pro Max",
      buildlog_path: "./fastlane/build_for_testing/buildlog_path",
      derived_data_path: "./fastlane/build_for_testing/derived_data_path",
      output_directory: "./fastlane/build_for_testing/output_directory"
   )
  end

  desc "Build & Run Unit Testing v2" 
  lane :start_testing do
    scan(
      workspace: "AlfaResto-RestoApp.xcworkspace",
      scheme: "AlfaResto-RestoApp",
      clean: true,
      verbose: true,
      only_testing: ["AlfaResto_Test"],
      skip_slack: true,
      result_bundle: true,
      output_xctestrun: true,
      build_for_testing: true,
      devices: ["iPhone 14 Pro Max"], # Note: 'device' is changed to 'devices'
      buildlog_path: "./fastlane/build_for_testing/buildlog_path",
      derived_data_path: "./fastlane/build_for_testing/derived_data_path",
      output_directory: "./fastlane/build_for_testing/output_directory"
    )
  end

  desc "Xcodebuid"
  lane :run_my_tests do
    scan(
      scheme: "AlfaResto-RestoApp",
      workspace: "AlfaResto-RestoApp.xcworkspace",
      device: "iPhone 15",  
    )
  end
end
