# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Pod Install"
  lane :pod_install do
    cocoapods(
      clean_install: false,
      use_bundle_exec: true,
      repo_update: false
    )
  end

  desc "Build & Run Unit Testing" 
  lane :start_testing do
    scan(
      scheme: "AlfaResto-RestoApp",
      workspace: "AlfaResto-RestoApp.xcworkspace",
      clean: true,
      device: "iPhone 15",
      buildlog_path: "./fastlane/build_for_testing/buildlog_path",
      derived_data_path: "./fastlane/build_for_testing/derived_data_path",
      output_directory: "./fastlane/build_for_testing/output_directory"
    )
  end
end
